export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const TOGGLE_SLIDE_PREFERENCE = 'TOGGLE_SLIDE_PREFERENCE';
export const CHANGE_MENU = 'CHANGE_MENU';
